---
title: '`*itscausal*`: Interrupted time series for real-world evidence'
subtitle: 'Causal Machine Learning with Counterfactual Prediction'
author: "Dr. Aurélien Sallin"
date: "10/10/2024"
echo: false
code-line-numbers: false
format:
  revealjs:
    width: 1280
    height: 720
    smaller: true
    embed-resources: true
    self-contained: true
    slide-number: c
    theme: swicatheme.scss
highlight-style: dracula # style to highlight code. Set background color in theme
cache: false
---

```{r set-options, echo=FALSE, cache=FALSE, warning=FALSE}
options(width = 100)
library(knitr)
knitr::opts_chunk$set(class.source = "chunkstyle")
```


## Background

- **Problem:** In many real-world scenarios, finding a credible control group is not feasible.
- **Example:** Health care policies often affect all providers simultaneously, like changes in physician compensation or changes in guidelines.
- **Challenge:** Standard methods, such as before-after comparisons or interrupted time-series (ITS), may produce biased estimates because of poor prediction, simplification assumptions with panel data, etc..

---

## Methods: ITSCausal Approach

- **ITSCausal:** A machine learning-based method addressing the "no control group" scenario.
- **Key Idea:**
  - Use machine learners and ensemble methods to train models on pre-intervention data.
  - Extrapolate based on the learned model into the post-intervention period.
  - Compare actual outcomes with predicted counterfactuals to estimate causal effects.
  
- **Estimates:**
  - **Individual Treatment Effects (ITEs):** Provides insights into effect heterogeneity.

---

## Uncertainty and Robustness

- **Uncertainty in Point-Estimates:**
  - Bootstrapping is used to quantify uncertainty.
  
- **Flexibility:** 
  - ITSCausal allows the use of different learners (random forest, gradient boosting, neural networks).
  - Hyperparameters can be fine-tuned for better performance.
  
---

## Results: User's Guide for ITSCausal

1. **Estimating Counterfactuals:**
   - Estimate causal effects from observational data.
   - Construct meaningful estimates even without a control group.
   
2. **Step-by-Step Guidance:**
   - Tune hyperparameters for various learners.
   - Select the best model for pre-intervention data.
   - Analyze and visualize intervention effects.
   
---

## Applications in Health Research

- **Public Health, Health Economics, and Health Services Research:**
  - ITSCausal is particularly useful with claims data.

- **Performance Examples:**
  1. Simulations of different data-generating processes.
  2. Evaluation of a reform in Switzerland that reduced physician fees.
  3. Comparison with experimental data on low-value care.

---

## Conclusion

- **ITSCausal:** A powerful tool for estimating causal effects without a control group.
- **Flexibility:** Can be applied across various fields, particularly in health research.
- **Future Directions:** Further application in public policy and health services.





